name: Preview CI/CD

on:
  push:
    branches: [ preview ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Set Current Date as Env Variable
        run: echo "NOW=$(date +'%Y%m%d.%H%M')" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore

      - name: Generate Preview Nuget Packages
        run: dotnet pack --version-suffix "preview.${{ env.NOW }}" --configuration Release

      - name: Publish Preview Packages to Github
        run: |
          dotnet nuget add source --username litenova --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/litenova/index.json"
          dotnet nuget push "src/**/bin/Release/*.nupkg" -s "github" --skip-duplicate
          